---
title: "guide_clustering_prototype"
author: "rainier"
date: "March 28, 2016"
output: html_document
---

```{r global_options, include=FALSE}
library(knitr)
library(ggplot2)
theme_set(theme_bw(base_size=12))
library(dplyr)
```

Hacky prototyping because I like dplyr.
In no way reflects my Python style as I have yet to find a PEP equivalent in R.

**PCA on numeric data** (no feature vectorizing yet)  
```{r}

guide_data = read.table("../data/example_guide_data.tsv", header=TRUE)

guide_data %>%
    select(-c(gene_name, spacer_id, spacer_seq)) %>%
    scale() %>%
    prcomp() ->
    pca_data
pca_data$rotation

rotation_data <- data.frame(pca_data$rotation, variable=row.names(pca_data$rotation))
arrow_style <- arrow(length = unit(0.05, "inches"),
                     type = "closed")
ggplot(rotation_data) + 
    geom_segment(aes(xend=PC1, yend=PC2), x=0, y=0, arrow=arrow_style) +
    geom_text(aes(x=PC1, y=PC2, label=variable), hjust=0, size=3, color='red') +
    xlim(-0.5, 0.5) +
    ylim(-0.5, 0.5) +
    coord_fixed()

percent <- 100*pca_data$sdev^2/sum(pca_data$sdev^2)
perc_data <- data.frame(percent=percent, PC=1:length(percent))
ggplot(perc_data, aes(x=PC, y=percent)) +
    geom_bar(stat="identity") +
    geom_text(aes(label=round(percent,2)), size=4, vjust=-.5) +
    ylim(0,80)

```

